export const dataTable = [
  {
    protocol_id: 1,
    protocol_name: "one",
    protocol_code: "ONE",
    is_active: 0,
    illness_data_json: "",
    protocol_reason: "",
    body_part_id: 20,
    body_sub_part_id: 30,
    scan_id: 40,
    standard_views_json: "",
    additional_views_json: "",
    comment: "test comment",
    description: [{ title: null, value: null }],
    require_contrast: 0,
    contrast_administration: "any text ",
    drl: "any text"
  },
  {
    protocol_id: 2,
    protocol_name: "one",
    protocol_code: "ONE",
    is_active: 1,
    illness_data_json: "",
    protocol_reason: "",
    body_part_id: 20,
    body_sub_part_id: 30,
    scan_id: 40,
    standard_views_json: "",
    additional_views_json: "",
    comment: "test comment",
    description: [{ title: null, value: null }],
    require_contrast: 0,
    contrast_administration: "any text ",
    drl: "any text"
  },
  {
    protocol_id: 3,
    protocol_name: "one",
    protocol_code: "ONE",
    is_active: 0,
    illness_data_json: "",
    protocol_reason: "",
    body_part_id: 20,
    body_sub_part_id: 30,
    scan_id: 40,
    standard_views_json: "",
    additional_views_json: "",
    comment: "test comment",
    description: [{ title: null, value: null }],
    require_contrast: 0,
    contrast_administration: "any text ",
    drl: "any text"
  }
];
